name: Update profiles in veraPDF-library

on:
  push:
    branches:
      [ master ]
    paths:
      - 'src/project/**'
      - 'src/oh/New.java'
      - '!src/project/sub/**'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Commit to state repository
        uses: drud/action-cross-commit@master
        with:
          source-folder: src/project
          destination-repository: https://irinamavrina:${{ secrets.WORKFLOW_TOKEN }}@github.com/irinamavrina/BusPuzzleNew
          destination-folder: src/main/java/project
          destination-branch: master
          git-user: "Git User"
          git-user-email: git-user@email.com
          git-commit-message: ${{ github.event.head_commit.message }}
          git-commit-sign-off: "false"
          excludes: sub/
      - name: Commit to state repository NEW
        uses: drud/action-cross-commit@master
          with:
            source-folder: src/oh
            destination-repository: https://irinamavrina:${{ secrets.WORKFLOW_TOKEN }}@github.com/irinamavrina/BusPuzzleNew
            destination-folder: src/main/java/project
            destination-branch: master
            git-user: "Git User"
            git-user-email: git-user@email.com
            git-commit-message: ${{ github.event.head_commit.message }}
            git-commit-sign-off: "false"
            excludes: sub/
#      - name: Make commit to library
#        uses: dmnemec/copy_file_to_another_repo_action@main
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.WORKFLOW_TOKEN }}
#        with:
#          source_file: 'src/project/Entry.java'
#          destination_repo: 'irinamavrina/BusPuzzleNew'
#          destination_folder: 'project'
#          destination_branch: 'master'
#          user_email: 'example@email.com'
#          user_name: 'rin'
#          commit_message: 'A custom message for the commit'
