name: Update profiles in veraPDF-library

on:
  push:
    branches:
      [ master ]
    paths:
      - 'project/**'
    paths-ignore:
      - 'project/sub/**' 


jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Make commit to library
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          source_file: 'Entry.java'
          destination_repo: 'irinamavrina/BusPuzzleNew'
          destination_folder: 'project'
          destination_branch: 'master'
          commit_message: 'A custom message for the commit'
